apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: joke-bot
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # Autoscaling
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        # Resource limits (lightweight)
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: REGION-docker.pkg.dev/PROJECT_ID/joke-bot/joke-bot:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: openrouter-api-key
              key: latest
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
          requests:
            cpu: '0.5'
            memory: 256Mi
